language: generic
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux

branches:
  only:
  - master
  - dev

before_script:
  # Update GCC Version
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # Download and Install SFML and Dev Dependencies
  - wget https://www.sfml-dev.org/files/SFML-2.4.2-linux-gcc-64-bit.tar.gz -O /tmp/sfml.tar.gz --no-check-certificate
  - tar -zxvf /tmp/sfml.tar.gz
  - sudo cp -r SFML-2.4.2/* /usr/
  - sudo apt-get install -y libjpeg62-dev libsndfile1-dev libglew1.5 libglew1.5-dev libfreetype6 libjpeg-turbo8 libjpeg8 libopenal-data libopenal1  libxrandr2 libxrender1 libsoil1

script: 
  - make